version: '3.8'
services:
   pg:
      image: postgres:17
      restart: unless-stopped
      container_name: pg
      env_file: ./.env.postgres
      volumes:
         - STGvolume:/var/lib/postgresql/data
      ports:
         - 5432:5432
      networks:
         - STGnet
volumes:
   STGvolume:
networks:
   STGnet:
      driver: bridge
